// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJ7FTckBXPk1BYu58RITWuHgOxEp07BA',
    appId: '1:150984937706:web:fce34a7a36b211c7698793',
    messagingSenderId: '150984937706',
    projectId: 'notes-d10e4',
    authDomain: 'notes-d10e4.firebaseapp.com',
    storageBucket: 'notes-d10e4.firebasestorage.app',
    measurementId: 'G-9RLC1MNBZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_i4N4sR-w4Rq5KvkamqmZARzq1PX44mY',
    appId: '1:150984937706:android:b823f4cb8f9d5752698793',
    messagingSenderId: '150984937706',
    projectId: 'notes-d10e4',
    storageBucket: 'notes-d10e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVacl9BjcxDuKplgd7Tde7Y1eJwhRumiM',
    appId: '1:150984937706:ios:0f80f7ec90e95cc7698793',
    messagingSenderId: '150984937706',
    projectId: 'notes-d10e4',
    storageBucket: 'notes-d10e4.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVacl9BjcxDuKplgd7Tde7Y1eJwhRumiM',
    appId: '1:150984937706:ios:0f80f7ec90e95cc7698793',
    messagingSenderId: '150984937706',
    projectId: 'notes-d10e4',
    storageBucket: 'notes-d10e4.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUJ7FTckBXPk1BYu58RITWuHgOxEp07BA',
    appId: '1:150984937706:web:f6ac6679d5b4a3ef698793',
    messagingSenderId: '150984937706',
    projectId: 'notes-d10e4',
    authDomain: 'notes-d10e4.firebaseapp.com',
    storageBucket: 'notes-d10e4.firebasestorage.app',
    measurementId: 'G-3PKPRBLC6L',
  );
}
