// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe75SbkJPvojVSrKi-0Hjb3q33qgcvnag',
    appId: '1:432041066831:web:f41763f3c4ebe5368c853a',
    messagingSenderId: '432041066831',
    projectId: 'goldmdp-44e19',
    authDomain: 'goldmdp-44e19.firebaseapp.com',
    databaseURL: 'https://goldmdp-44e19-default-rtdb.firebaseio.com',
    storageBucket: 'goldmdp-44e19.firebasestorage.app',
    measurementId: 'G-Q45GW0WLGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoX_QqFxvnsdmfR93qz_fmAq-gUUjMV7M',
    appId: '1:432041066831:android:bb73ccd293584f3c8c853a',
    messagingSenderId: '432041066831',
    projectId: 'goldmdp-44e19',
    databaseURL: 'https://goldmdp-44e19-default-rtdb.firebaseio.com',
    storageBucket: 'goldmdp-44e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9BKKOgX9SQ5z8Sq0jy4tRrNdY6lAbkk',
    appId: '1:432041066831:ios:ecfd4710c999cd6e8c853a',
    messagingSenderId: '432041066831',
    projectId: 'goldmdp-44e19',
    databaseURL: 'https://goldmdp-44e19-default-rtdb.firebaseio.com',
    storageBucket: 'goldmdp-44e19.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9BKKOgX9SQ5z8Sq0jy4tRrNdY6lAbkk',
    appId: '1:432041066831:ios:ecfd4710c999cd6e8c853a',
    messagingSenderId: '432041066831',
    projectId: 'goldmdp-44e19',
    databaseURL: 'https://goldmdp-44e19-default-rtdb.firebaseio.com',
    storageBucket: 'goldmdp-44e19.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe75SbkJPvojVSrKi-0Hjb3q33qgcvnag',
    appId: '1:432041066831:web:1c5ab35935b9ef8e8c853a',
    messagingSenderId: '432041066831',
    projectId: 'goldmdp-44e19',
    authDomain: 'goldmdp-44e19.firebaseapp.com',
    databaseURL: 'https://goldmdp-44e19-default-rtdb.firebaseio.com',
    storageBucket: 'goldmdp-44e19.firebasestorage.app',
    measurementId: 'G-3V5LCSMDX2',
  );
}
